### ISSUE TITLE
Null-condition operations aren't recognised

### ISSUE THREAD

**Issue by mikesena** [BADF00D/DisposableFixer#48] opened 2017-07-12 01:18 UTC
Hey mate;

LOVE the extension.  It's so easy to forget to properly dispose of objects, and I appreciate the time you've put in getting this one done.

It seems pretty good to me, but I've found it doesn't recognise null-condition operations.  For example:
```
private IDisposable _toDispose;

public void OptionalCall() {
    _toDispose = File.Open("");
}

public void Dispose() {
    _toDispose?.Dispose();
}
```

Is that something that can be added?

**Comment by BADF00D** [comment] 2017-07-12 09:07
Thanks for the compliment and the bug report. 
Actually I stumbled upon this error a while ago. But I thought I fixed it in issue #33. Can you check which version you are using? It should be fixed since version 0.21.

I can see, that the [test that verifies this issue](https://github.com/BADF00D/DisposableFixer/blob/master/src/DisposeableFixer/DisposeableFixer/DisposeableFixer.Test/IssueTests/If_Analyser_runs_on_code_from_issue_33.cs) only test local variables, maybe its not correctly detected when used on fields.

**Comment by mikesena** [comment] 2017-07-12 09:26
I'm not able to check; I've left the office for the day, so it'll be my tomorrow.  l did only install it about 10 hours ago however; should that be the latest? 

I'm on Visual Studio 2017, C# 7.0.

**Comment by BADF00D** [comment] 2017-07-12 10:10
It should be version 0.24. So I thinks its a bug when using null-conditional operator on disposed on @badf00d: added test for null-conditional operator for
- fields,
- local variables
- method invocations.

**Comment by mikesena** [comment] 2017-07-13 06:44
Hey @BADF00D; checked, and I'm running 0.24.
How can I help you work this out?

**Comment by BADF00D** [comment] 2017-07-13 06:55
It would be nice if you could create a small code sample that reproduces the problem using only classes from mscorelib.  You can see such an example in this [test](https://github.com/BADF00D/DisposableFixer/blob/master/src/DisposeableFixer/DisposeableFixer/DisposeableFixer.Test/IssueTests/If_Analyser_runs_on_code_from_issue_33.cs).

Usually I work test driven, so you can spare me time writing the test. Thanks for your help

**Comment by mikesena** [comment] 2017-07-13 07:53
Sure; here you go.

> Marker: Field is not disposed.

```c#
using System;
using System.Reactive.Disposables;

namespace MyNamespace
{
    internal class MyClass : IDisposable
    {
        private readonly IDisposable _exampleDisposable;

        public MyClass()
        {
            _exampleDisposable = Disposable.Create(() => { });
        }

        public void Dispose()
        {
            _exampleDisposable?.Dispose();
        }
    }
}
```


> ** *(No marker is displayed)* **

```c#
using System;
using System.Reactive.Disposables;

namespace MyNamespace
{
    internal class MyClass : IDisposable
    {
        private readonly IDisposable _exampleDisposable;

        public MyClass()
        {
            _exampleDisposable = Disposable.Create(() => { });
        }

        public void Dispose()
        {
            _exampleDisposable.Dispose();
        }
    }
}
```

**Comment by BADF00D** [comment] 2017-07-13 20:02
I just uploaded version 0.25 that should fix the problem. I found out, that there was a problem with MethodInvocation, too.

The following example yields an error before, but it shouldn't:
```csharp
using System.IO;
using System.Threading.Tasks;
namespace DisFixerTest.Async
{
    internal class MyClass : IDisposable
    {
        public MyClass()
        {
            Create()?.Dispose();
        }

        public IDisposable Create()
        {
            return new System.IO.MemoryStream();
        }
    }
}
```
This and your bug are fixed now.

**Closed** 2017-07-13 20:07 UTC
Labels: bug

**Comment by mikesena** [comment] 2017-07-13 23:55
Verified!  Thanks @BADF00D
