### ISSUE TITLE
Method that are returning disposable object, the return object shouldn't marked inside the method

### ISSUE THREAD

**Issue by mhamri** [BADF00D/DisposableFixer#38] opened 2017-06-12 04:16 UTC
this is a method that i have, using asp.net core 1.2

method is returning a disposable object that shouldn't be marked as a warning inside the method. moreover it's base asp.net core class. (this one and ILogger, for both i get this wiggly marker under them)
```

public static IServiceProvider CompileAndUseDefaultServices(this IServiceCollection serviceCollection, IConfiguration configuration)
        {
            var serviceProvider = serviceCollection
                .BuildServiceProvider();

           //following lines marked as an error. but i'm returning the service provider in this function. BTW it's asp.net core base class. can't dispose it 
            serviceProvider.GetService<ILoggerFactory>()
                .AddConsole(configuration.GetSection("Logging:Console"))
                .AddProvider(new LoggerFileProvider(configuration.GetSection("Logging:File")));

            return serviceProvider;
        }
```

**Comment by BADF00D** [comment] 2017-06-12 04:56
@mhamri Thanks for reporting the bug.

What is the return type of
```csharp
serviceProvider.GetService<ILoggerFactory>()
     .AddConsole(configuration.GetSection("Logging:Console"))
     .AddProvider(new LoggerFileProvider(configuration.GetSection("Logging:File")));
```
Is this ILoggerFactory and does it implement IDisposable?

**Comment by mhamri** [comment] 2017-06-12 05:00
yes return type is iLoggerFactory

this is the ILoggerFactory:

```
    //
    // Summary:
    //     Represents a type used to configure the logging system and create instances of
    //     Microsoft.Extensions.Logging.ILogger from the registered Microsoft.Extensions.Logging.ILoggerProviders.
    public interface ILoggerFactory : IDisposable
    {
        //
        // Summary:
        //     Adds an Microsoft.Extensions.Logging.ILoggerProvider to the logging system.
        //
        // Parameters:
        //   provider:
        //     The Microsoft.Extensions.Logging.ILoggerProvider.
        void AddProvider(ILoggerProvider provider);
        //
        // Summary:
        //     Creates a new Microsoft.Extensions.Logging.ILogger instance.
        //
        // Parameters:
        //   categoryName:
        //     The category name for messages produced by the logger.
        //
        // Returns:
        //     The Microsoft.Extensions.Logging.ILogger.
        ILogger CreateLogger(string categoryName);
    }
```

**Comment by BADF00D** [comment] 2017-06-12 05:16
It seems to me, that this is one in a few cases, that should not be disposed. Unfortunately I was not able to figure out a way, to automatically detect this situations. Currently I use a list of types, that should be ignored during disposable detection. 
From [DefaultConfiguration](https://github.com/BADF00D/DisposableFixer/blob/master/src/DisposeableFixer/DisposeableFixer/DisposableFixer/Configuration/DefaultConfiguration.cs):
```csharp
IgnoredInterfaces = new HashSet<string> {
    "System.Collections.Generic.IEnumerator"
};
IgnoredTypes = new HashSet<string> {
    "System.Threading.Tasks.Task",
};
```

This list is currently hard-coded, but there is a plan to make this configurable in ticket #15. For a short-term solution, I can add this interface to the hard-coded items. Is the full name ```Microsoft.Extensions.Logging.ILoggerFactory```?

**Comment by mhamri** [comment] 2017-06-12 07:06
thanks, yes, it's the full name

**Comment by BADF00D** [comment] 2017-06-15 20:56
I just uploaded v0.21. can you Verify the fix?

**Comment by mhamri** [comment] 2017-06-28 10:07
hi, I tried on vs2015 and v2017, both looks like has the problem. still, i'm getting the warning for `ILoggerFactory`.

**Comment by BADF00D** [comment] 2017-07-07 06:00
I'm still not able to reproduce the problem. But I stumbled upon the [original source code](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/ILoggerFactory.cs), so maybe this helps to reproduce the problem.

At the moment, the only difference I can see  is, that the namespace from ILoggerFactory does not match its folder structure. But this should not matter at all.

**Comment by BADF00D** [comment] 2017-09-28 18:03
Finally I was able to reproduce the problem. There was actually a bug that causes the problem. I added a few test, so the problem should not occur any more.

Will be part of release 0.33.

**Closed by BADF00D** 2017-09-28 18:03 UTC
Labels: await reply, enhancement
